#################################################
### S P R I N G   C O N F I G U R A T I I O N ###
#################################################
spring:
  cloud:
    config:
      # Config server configuration.
      server:
        monitor:
          github:
            enabled: true
        git:
          uri: ${GIT_URI:[{nube.configuration-files.git.uri}]}
          ignore-local-ssh-settings: true
          host-key: AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          host-key-algorithm: ssh-rsa
          private-key: |
                        -----BEGIN RSA PRIVATE KEY-----
                        Proc-Type: 4,ENCRYPTED
                        DEK-Info: AES-128-CBC,6B5F2E484FDF72F795EA18BDCD1F3017

                        0YQDYoCewZ8iPxRjXEKspBwcHCZce3OOJf6g/KJS0a34mwuU4VjGW9iiqttsu/zy
                        S4NOQM/1j6UZpN9CFH6GfRxB1ixKq+l3Bei+CEc48os7OsuR3S2DKWVgEA7PC1iT
                        KeWxzh6HpWqnimwTWJhCKfPVd6Ep6x4GxRgmEJpCs5xBzt1rGqSqUhPMDltgfUqG
                        W29CR0r9NGdVpzoBBEpQi9xGLP6Uc0mXIH1Y5URqpCW4zB2GeBLL4N2p9KF89Pfg
                        RSfYQYCVW+SHENGuO4K5Lj2h5GDR4kJmLFjIdvxSWfsdB58wMPCagFSmQsklSuYr
                        0Q4+tVrGbzuPuepBj8p3znbxS5kvRkEMZLNdv0He6UZzy7i+I5CM8OcJahbpfyAj
                        Nkzfm1N9v8TDdSJUUyj1SLMa9/szYOWG9Hy0bwKPmrCk+o7xx+MiOp+Q1luOPgsA
                        9AOPSaf6YC0RSZpa7uPAysa2jFSsaj/wRaFaOVWzbt3SZuTN5Uw28THuGYEFHa38
                        GAYSQhx4DWTpUNsLzel4ONjDYlFCF86UIa4JNkCUQCRFgge0gEn/ixaQvBp1HcjN
                        qeMMZqWYbHJm+E6H8hxjCSZG0vL+8LcbhSbf2ezZyJd/ZZC2aKpYK5sjQGnEu0S+
                        gskoWv+1p54+X+X9J9q/KoA2l5nuWK+CuFzTO/EwNDgoTm9sNBiW44xXjvSTAMpZ
                        dc7VY+GDjoOjoRarQQb7Gph/qjBLMHq2NOVNCQOLDt9Rq84ezfHUsRfR9bAjZPj0
                        fzj0EmkaoN7W8Qv8J3w4jqRq5DozKLKmhZL/W/+xh4pW7qwqreaP/+X3KM95PfwQ
                        GLPYZ7z0ZTLlxNLonq4q5gG51w2iGeuT+WaiZEfm9HWLk3ZfurHSk2P0OVbEb7VA
                        SkFIZ/aX0d7fOE5ocjFPufrdSG8D2mQLrJmX7wtt8Y2RJJRo1jouT1ePuFX9QAzR
                        AZTMDAXP17WALYEb7UiX3K3PXi6DHGC9bsBoDKWwg3dRoE9sw08UmJyXxa+Xps2z
                        eZoRCMsemmREHnc/SOWjRNF62YIz2YiIbtgNFHFMbV4HkShEFxyV3+Frj/X5Yp0Z
                        Hs7XVbnxx6Rc9Qq6neOVsubxKQgs29n8lTXIMVtQnHlbERxkkpboTo1XRzpz5F9E
                        c4mYa7kccXYUPqiHZPl9OEljrWw5mASCT4TEr0yTaCx5iZqzRFQnCRdERXDYZK/J
                        qCafOJsmE+kFwIBMkCmD1TXwiL87iFjtb1vf4W82tLKPyKX+ILzDEP3xwgGHaKKw
                        Ak+boOZpwoQcLl0qn6uglh78Svy/Nkg1prP96IfXj+EBji1t2cT8nbWNQ+UqKREX
                        Zl+odtkkazoF9Lo1Jy+82SROLDdw2avSSMNriAprX2eayz+9d7BpyRVkirvtCagM
                        TijxNeLAJHnxe5lmLuVTerJsqPvM3XCVTVYZGn7tEKQOFsZ/5mgiC6svbcs+UBJG
                        GQiEJlH6krQ92YEPwJHv2CdexDWuUfh65MkQMAz0e4gWtI98vQh8+uWXLtOBRGOt
                        Gym+dhlEaCwUcNo1UflLRS2MZfm25Oi8Zj6wIYpdl+x8dUoJWOOEa9QUTsW5Szhr
                        asZEdtr+9B3KAlgxC8MyflUxLYET1bchfeseaYAjZPRG7lAYRA9u3WXk7Tj/bNCz
                        RCFzJ9HWrO9p3jm7JEQOI5loqVOSmaitWpfz9GmgdRvFgbiewbGqibpYO04x/u+e
                        kD37OOvnYKA/OJwexbK37Rf3N8JsrW+9kg2swOL+VxxMcrnB7/lYYW2MzusAA94W
                        0S0GU4d/tnvic5f3HAHg+LExxPC5vhJAWmXo/xm6DsGfla3FvfknHi33GNzaT9q4
                        Low7HWG2UIG/ySMGDmErxDUp+JGvq/v4Y5+OI3VLyQr3a0WfoZRXzGJaVrZFuX+U
                        qmiNUjdT+r1uXr7vUMVuiNnD1X9BEV56qQcKfD5b+G6rDQdYNTu+x5gvWpAEx4hO
                        JjUdm8o6KUygvs1/BiR30dU8nnmSQmDTACEjH46domkzVZ1lyEti5xFLXUtEB5xe
                        kKtyFVHFFdsxym3s2TITbZOy2t49lBZ5Gn3Smj6syFipC+TrTDb5tHOU0mgakjAE
                        o7N8aWlJ2g+agfZHgqIKoHaeqSzCRTyPnaRp3JPAawic/8VXCx1CfHa5cXOvCanf
                        D1vL9CERqYjWGcs0Pl7mCBaK99pFotBRsQaenCUXg6F+2VuRVHq4Z1N2mJfwMgFD
                        TDm3AzLMNyR3xQrD+j+OiULHU09VHG+PfryhjVF5XUTLFxwlcQqzga6Sxaxq7yYa
                        Zi0EpkuFMRKScn+U4sgWjiOx0Sagdark8NyQyI4pBbojjfBAEWxLZhf+XjLUECBi
                        Wsf8l2uVeYed/bBrWnPdYW0XXXP8bhaJG2cKnxD3NT6G+xgywJSZ+mZsF2krbePE
                        dq5W++BDes8gDPzy8vJz93GPzkrVYBqyPZrA7PyDS2JfnJUcqHoBEKqbLi8hLPLv
                        3MVd1FhhRw1MzBDCQV7lQ6h3AZVv4WE/73fZm1W4nO042efWa45iyCmrvEO57SuM
                        EeU4cIa60TOZ3R+2JC/zKM3E07Ko7k/mSvxAbpcEVSQFlHjfT5otypdbqnf0+OIZ
                        Mf6h7OZ0JXCslIwR32VDe5e3Mqb/iMVYvQts3E3/pR3YGe1a6ZH3e1ioTnkZftJB
                        QvBzFlY1JujpGaViz7QfVb/p5vw05XjFR6pWI+HKH/a8txxT2pVie8k/ewop3nOx
                        RAlKE5ru+hTjUTu6YfYix0f8EbPp0wk7lnctQyvFt9QJhAoKOoXWtemSPt7lJc3B
                        aPzjd268r9I3rsiu/jhZVEG8CEVF43K81+CoacqhLripdZrrY2HwOSPs/ikEHo8R
                        9Z3NT/an7Y9vsAwQZVcWlUV6y64dc2S6zp0sBTsPvDpGmVQ4vq5fuU12Ns3bkfwp
                        g8S2m/yaWPulIRh27Dq4liRQ/LZkED6xQxlFemfqAaTiBAdrv1OHBwhCzPvHiO3r
                        +8K/ZRJpNE5gx9PR6/WemN/evyLhKOogp9CmAvc8ZXw/oMF+hWTPIna/wlevuLvl
                        sQm/FS+EKIK7kie1hGQn3kfZlVCpahDJNp2rHQAj2BCesf/r4Rp0uryqYe1X0Z7a
                        -----END RSA PRIVATE KEY-----
          passphrase: WTqMEzJ9pEDxpKjXHTD2L97c

      # Discovery client activation.
      discovery:
        enabled: true
  # Enable ansi colors for default spring logging.
  output:
    ansi:
      enabled: always
  # RabbitMQ configuration.
  rabbitmq:
    host: [{rabbitmq.host}]
    port: [{rabbitmq.port}]
    username: [{rabbitmq.username}]
    password: [{rabbitmq.password}]
  # Zipkin configuration.
  zipkin:
    discovery-client-enabled: true
    enabled: true
    locator:
      discovery:
        enabled: true
    service:
      name: [{nube.configurator-service.application.name}]
###################################################################
### D I S C O V E R Y   C L I E N T   C O N F I G U R A T I O N ###
###################################################################
# Discovery client health check activation.
# [WARNING] This property must set in application.yml instead bootstrap.yml to avoid malfunction problems.
eureka:
  client:
    healthcheck:
      enabled: true
###########################
### M A N A G E M E N T ###
###########################
management:
  endpoints:
    enabled-by-default: true
#################################################
### L O G G I N G   C O N F I G U R A T I O N ###
#################################################
logging:
  register-shutdown-hook: true
  level:
    root: ${LOGGING_LEVEL:[{nube.logging.level}]}
###############################################
### R I B B O N   C O N F I G U R A T I O N ###
###############################################
ribbon:
  # Enable Ribbon load balancer on discovery service.
  eureka:
    enabled: true
#######################################
### C U S T O M   P R O P E R I E S ###
#######################################
nube:
  service:
    security:
      username: [{nube.configurator-service.security.username}]
      password: [{nube.configurator-service.security.password}]
      roles: [{nube.configurator-service.security.roles}]